### ISSUE TITLE
Example .conf 

### ISSUE THREAD

**Issue by bt-maps** [InsideZhou/lua-resty-pubsub#1]
Do you have a simple  example of using this with openresty. Maybe an example .conf or location with a Lua script. I am unsure in which phase  (init by Lua, content by Lua) to use it in.

**Comment by InsideZhou** [comment]
@bt-maps  Here is my conf for nginx.

```
location /pubsub {
    access_log              off;
    error_log               logs/api.log.ws debug;
    lua_socket_log_errors   off;
    content_by_lua_file     /var/local/pubsub/websocket.lua;
}
```
